/**
 * 情境记忆存储
 * 职责单一：存储和检索任务摘要
 * @module task-monitor/lib/memory/EpisodicMemoryStorage
 */

import { TaskSummary } from './types';
import { writeFile, mkdir } from 'fs/promises';
import { join } from 'path';
import * as lockfile from 'proper-lockfile';

/**
 * OpenClaw Api 接口（简化定义）
 */
interface Api {
  logger: {
    info?: (message: string, ...args: any[]) => void;
    error?: (message: string, ...args: any[]) => void;
    warn?: (message: string, ...args: any[]) => void;
  };
}

/**
 * 情境记忆存储
 * 负责将任务摘要持久化到文件系统
 */
export class EpisodicMemoryStorage {
  private consolidationPath: string;

  /**
   * 构造函数
   * @param api OpenClaw Api 实例，用于日志记录
   * @param consolidationPath 情境记忆存储路径
   */
  constructor(
    private api: Api,
    consolidationPath: string
  ) {
    this.consolidationPath = consolidationPath;
  }

  /**
   * 保存任务摘要（异步 + 文件锁）
   * @param summary 任务摘要对象
   * @throws 文件操作失败时抛出异常
   */
  public async saveTaskSummary(summary: TaskSummary): Promise<void> {
    const date = new Date().toISOString().split('T')[0];
    const filename = `${date}-${summary.id}.md`;
    const filepath = join(this.consolidationPath, 'tasks/completed', filename);
    const dir = join(this.consolidationPath, 'tasks/completed');

    let release: (() => Promise<void>) | null = null;

    try {
      // 确保目录存在（递归创建）
      await mkdir(dir, { recursive: true });

      // 使用文件锁（异步）
      release = await lockfile.lock(filepath, { retries: 3 });

      // 格式化并写入文件
      const content = this.formatTaskSummary(summary);
      await writeFile(filepath, content, 'utf-8');

      this.api.logger.info?.(`[memory-storage] Task summary saved: ${summary.id}`);
    } catch (error) {
      this.api.logger.error?.(
        `[memory-storage] Failed to save task summary: ${summary.id}`,
        error
      );
      throw error;
    } finally {
      // 确保释放文件锁
      if (release) {
        try {
          await release();
        } catch (unlockError) {
          this.api.logger.warn?.(
            `[memory-storage] Failed to release lock for: ${summary.id}`,
            unlockError
          );
        }
      }
    }
  }

  /**
   * 格式化任务摘要为 Markdown
   * @param summary 任务摘要对象
   * @returns 格式化后的 Markdown 字符串
   */
  private formatTaskSummary(summary: TaskSummary): string {
    const endTimeStr = new Date(summary.endTime).toLocaleString('zh-CN', {
      timeZone: 'Asia/Shanghai',
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit'
    });

    const generatedTime = new Date().toISOString();

    return `# 任务摘要 - ${summary.name}

**完成时间**: ${endTimeStr}
**任务类型**: ${summary.type}
**状态**: ${summary.status}

## 任务目标
${summary.goals.length > 0 ? summary.goals.map(g => `- ${g}`).join('\n') : '- 未提取到目标'}

## 关键成果
${summary.achievements.length > 0 ? summary.achievements.map(a => `- ${a}`).join('\n') : '- 未提取到成果'}

## 遇到的问题
${summary.problems.length > 0 ? summary.problems.map(p => `- ${p.problem} → 解决方案：${p.solution}`).join('\n') : '- 无'}

## 经验教训
${summary.lessons.length > 0 ? summary.lessons.map(l => `- ${l}`).join('\n') : '- 无'}

## 相关文件
${summary.files.length > 0 ? summary.files.map(f => `- ${f}`).join('\n') : '- 无'}

---
*Generated by task-monitor memory-manager on ${generatedTime}*
`;
  }
}
